# Generated by Django 5.1.2 on 2024-11-11 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list', '0002_task_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachment',
            name='description',
        ),
        migrations.AlterField(
            model_name='attachment',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
