# Generated by Django 5.1.2 on 2024-11-12 13:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list', '0003_remove_attachment_description_alter_attachment_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='environment',
            name='collaborators',
            field=models.ManyToManyField(blank=True, related_name='collaborated_environments', to=settings.AUTH_USER_MODEL),
        ),
    ]
